### PR TITLE
Kvmi v7++

### PR DESCRIPTION
**Pull request by adlazar**
This PR has the basic introspection patches [kvmi-v7](https://lore.kernel.org/kvm/20200207181636.1065-1-alazar@bitdefender.com/) submitted on kvm list with some fixes on top of Linux 5.4.24 (commit cff670b3eb68, tag v5.4.24 from git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git), plus:
- alternate EPT views support (only for rwx, not for content)
- virtualization exceptions
- remote mapping (when the introspection app runs on a different VM)
- Sub-page protection
- tools/kvm/kvmi from kvmi-v6 branch

The kernel KVMI headers from tools/kvm/kvmi are kept in the kvmi-v6 format (eg. kvmi_inject_exception instead of kvmi_vcpu_inject_exception). However, one structure is not binary compatible (kvmi_event_trap) and you need to rebuild the userspace tools or change the headers used to build the kernel.

I didn't test the kvmi_test.c tool yet.

### CODE REVIEW

**Comment by Wenzel** [comment]
@adlazar the [`kvmi-v7`](https://github.com/KVM-VMI/kvm/tree/kvmi-v7) has been pushed based on this PR.

I changed the base to this branch, so it doesn't create any conflict.

**Comment by adlazar** [comment]
Now, we only have the changes to libkvmi.c: new functions for SPP, EPT-views, VMFUNC, #VE, two bug-fixes and a small documentation update.

**Comment by Wenzel** [comment]
@adlazar I think I had a better idea for people to view the changes from this PR.

I will rewrite the branch that I have already pushed (`kvmi-v7`) to point to your base commit: `cff670b3eb68257029e2977a6bfeac7d9b829e9a` (`v5.4.24`).

Therefore in this PR we will see your commits only, without those from the KVM/Linux community.
What do you think ?

**Comment by Wenzel** [comment]
Basically:

~~~
git branch -f kvmi-v7 cff670b3eb68257029e2977a6bfeac7d9b829e9a
git push origin kvmi-v7 --force
~~~

**Comment by adlazar** [comment]
Great!

**Comment by Wenzel** [comment]
Okay, this looks much better now.
We can see your `190` commits on top of `5.4.24`

**Comment by Wenzel** [comment]
@adlazar can I merged this PR, or you are still adding new commits as `kvmi-v7` and you prefer to keep it opened ?

**Comment by adlazar** [comment]
@Wenzel, you can merge this PR, thanks.

**Pull request merged**
