### PR TITLE
Update to RFC v5

### PR DESCRIPTION
**Pull request by adlazar**
The KVMI patches were applied on 3cf85f9f6bd7 (KVM: x86: nSVM: fix switch to guest mmu).

### CODE REVIEW

**Comment by Wenzel** [comment]
I would be happy to merge this PR, but it has a different base than the one you use in `kvmi` branch, hence the merge conflict.

I'm wondering if we should force and rewrite the `kvmi` branch with these new commits, or if there is a better solution ? :thinking:

**Comment by adlazar** [comment]
> I'm wondering if we should force and rewrite the `kvmi` branch with these new commits, or if there is a better solution ? thinking

Unfortunately, for kernel code and `libkvmi.c` it is difficult, at least for a while, to merge the commits as they are from the development repository.

I would do two branches in all three repositories: kvmi + kvmi5

**Comment by Wenzel** [comment]
I'm wondering how much people are aware of the `kvmi` branches as of today, and in this subset, how much actually uses them ?

I would like to avoid creating confusion in the branches as much as possible, hence keeping `kvmi` only.

**Comment by Wenzel** [comment]
Also ping @tklengyel , if you have an opinion on the matter.

**Comment by tklengyel** [comment]
I would say keeping a single branch is better then having mulitple. They are all dev branches so people likely will be only interested in the "latest".

**Comment by Wenzel** [comment]
I'm ok for rewriting `kvmi`'s history and pushing this branch commits instead.
I can do this tonight, since everyone seems to agree.
@tklengyel , @adlazar

**Comment by Wenzel** [comment]
The branch `kvmi` has been rewritten.
I don't get why this PR is marked as having merge conflicts :thinking:

**Comment by Wenzel** [comment]
weird because the QEMU one worked well, marked as merged now:
https://github.com/KVM-VMI/qemu/pull/3

**Pull request closed without merging**
