### PR TITLE
kvmi: increase the message size

### PR DESCRIPTION
**Pull request by adlazar**
This will allow us to read a whole page with KVMI_READ_PHYSICAL.

Signed-off-by: Adalbert Lazăr <alazar@bitdefender.com>

### CODE REVIEW

**Comment by mtarral** [comment]
@adlazar could you explain this modification, because it's not obvious to me why we are introducing a magic number `* 2` to increase the message size ?

**Comment by adlazar** [comment]
For convenience, we've tried to keep the message limit small and page size multiple (including the message header). The variable size commands and command replies are affected by this limit. The old value (one page size minus the message header) won't allow us to read (or write) a whole page, which is a common use case, I guess.

**Comment by mtarral** [comment]
@adlazar can i merge this, or do you need more eyes/testing on it ?

**Comment by adlazar** [comment]
You can merge it, but you need it in userspace (libvmi) too.

**Comment by Wenzel** [comment]
I forgot about this one, merging now.

**Pull request merged**
