### PR TITLE
support for handling cpuid event added

### PR DESCRIPTION
**Pull request by 0xarash**

### CODE REVIEW

**Comment by Wenzel** [comment]
sorry for the lack of feedback @0xarash ,
@mdontu, @adlazar, can you take a look ?

**Comment by 0xarash** [comment]
> sorry for the lack of feedback @0xarash ,
> @mdontu, @adlazar, can you take a look ?

@wenzel It's OK :)

**Comment by adlazar** [comment]
It looks good.

**Comment by 0xarash** [comment]
Apparently my branch had a conflict with new kvmi-v7 branch, I merged the kvmi-v7 into mine to fix it.

**Comment by adlazar** [comment]
@0xarash, you can have a look at https://github.com/KVM-VMI/kvm/blob/kvmi-v7/tools/testing/selftests/kvm/x86_64/kvmi_test.c and see if you could add a test for this new event. It should look like`test_event_xsetbv()`.
The scripts used with Travis CI run something like:
`make -C tools/testing/selftests/kvm TEST_GEN_PROGS_x86_64=x86_64/kvmi_test run_tests DEBUG=1` (when the KVMI kernel is active)

**Comment by 0xarash** [comment]
@adlazar, OK first chance I would take a look.

**Pull request merged**
