### PR TITLE
Kvmi v7 updates

### PR DESCRIPTION
**Pull request by adlazar**
- new vCPU commands: KVMI_VCPU_GET_XCR, KVMI_VCPU_SET_XSAVE and KVMI_VCPU_CHANGE_GFN
- the remote memory mapping feature is re-implemented ([needs a new QEMU](https://github.com/KVM-VMI/qemu/pull/7))
- the memory consumption (when using multiple EPT-views) is reduced (and it will be easier to add a default access right/tracking for an EPT view) 
- the dependencies for CONFIG_REMOTE_MAPPING and CONFIG_KVM_INTROSPECTION_GUEST are changed. Please make sure that CONFIG_MEMORY_HOTPLUG + CONFIG_ACPI_HOTPLUG_MEMORY are enabled and CONFIG_TRANSPARENT_HUGEPAGE is disabled.

### CODE REVIEW

**Comment by Wenzel** [comment]
I started a CI build to test these changes:
https://travis-ci.com/github/KVM-VMI/kvm-vmi/builds/213009679

the build will use the old QEMU (2.11.93)

**Comment by Wenzel** [comment]
The buiild failed, there is a compilation issue with KVM:
https://travis-ci.com/github/KVM-VMI/kvm-vmi/builds/213009679#L739

The output is not very friendly, i converted it:

<details>
  <summary>Click to expand make output</summary>

~~~
"In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/../../../virt/kvm/kvm_main.c:18:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/../../../virt/kvm/coalesced_mmio.c:14:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/../../../virt/kvm/eventfd.c:12:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/../../../virt/kvm/irqchip.c:15:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/../../../virt/kvm/vfio.c:11:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/../../../virt/kvm/async_pf.c:11:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/x86.c:19:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/irq.h:15,
                 from arch/x86/kvm/mmu.c:18:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/emulate.c:21:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/irq.h:15,
                 from arch/x86/kvm/i8259.c:32:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/irq.c:12:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/lapic.c:19:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/i8254.c:35:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/ioapic.c:30:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/irq_comm.c:12:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/cpuid.c:12:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/pmu.c:14:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/mtrr.c:17:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/x86.h:5,
                 from arch/x86/kvm/hyperv.c:21:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/page_track.c:14:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/debugfs.c:7:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/vmx/vmx.c:20:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/vmx/pmu_intel.c:12:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/lapic.h:7,
                 from arch/x86/kvm/vmx/capabilities.h:7,
                 from arch/x86/kvm/vmx/vmcs.h:12,
                 from arch/x86/kvm/vmx/vmcs12.h:7,
                 from arch/x86/kvm/vmx/vmcs12.c:3:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/vmx/../hyperv.h:24,
                 from arch/x86/kvm/vmx/evmcs.c:6:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/x86.h:5,
                 from arch/x86/kvm/cpuid.h:5,
                 from arch/x86/kvm/vmx/nested.c:9:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/svm.c:17:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:38,
                 from arch/x86/kvm/pmu_amd.c:13:
./include/linux/kvmi_host.h: In function ‘kvmi_enter_guest’:
./include/linux/kvmi_host.h:165:13: warning: ‘return’ with a value, in function returning void
    { return true; }
             ^~~~
./include/linux/kvmi_host.h:164:20: note: declared here
 static inline void kvmi_enter_guest(struct kvm_vcpu *vcpu)
                    ^~~~~~~~~~~~~~~~
ld: arch/x86/../../virt/kvm/coalesced_mmio.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/../../virt/kvm/eventfd.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/../../virt/kvm/irqchip.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/../../virt/kvm/vfio.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/../../virt/kvm/async_pf.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/x86.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/mmu.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/emulate.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/i8259.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/irq.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/lapic.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/i8254.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/ioapic.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/irq_comm.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/cpuid.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/pmu.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/mtrr.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/hyperv.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/page_track.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/debugfs.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/vmx/vmx.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/vmx/pmu_intel.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/vmx/vmcs12.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/vmx/evmcs.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/vmx/nested.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/svm.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
ld: arch/x86/kvm/pmu_amd.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
make: *** [Makefile:1076: vmlinux] Error 1"
~~~

</details>

Error is:
~~~
ld: arch/x86/../../virt/kvm/coalesced_mmio.o: in function `kvmi_update_ad_flags':
/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: multiple definition of `kvmi_update_ad_flags'; arch/x86/../../virt/kvm/kvm_main.o:/vagrant/kvm/./arch/x86/include/asm/kvmi_host.h:87: first defined here
~~~

**Comment by Wenzel** [comment]
I tried to compile on my machine, and it works.
I will investigate the CI to see what went wrong

**Comment by adlazar** [comment]
The warnings/errors are valid, but they should happen only when KVM_INTROSPECTION is not set. Maybe because (now) it depends on transparent hugepages not being enabled.

```
config KVM_INTROSPECTION
	bool "KVM Introspection"
	depends on KVM && (KVM_INTEL || KVM_AMD) && !TRANSPARENT_HUGEPAGE

```
That condition should placed on REMOTE_MAPPING only. 
I'll make the necessarily changes.

Keep in mind that in order to enable REMOTE_MAPPING, you have to disable TRANSPARENT_HUGEPAGE (which is enabled by default) and enable MEMORY_HOTPLUG + ACPI_HOTPLUG_MEMORY.

**Comment by adlazar** [comment]
The last `push -f` was to update d843b47, sorry.

**Comment by Wenzel** [comment]
Merging this one, thank you @adlazar !

**Pull request merged**
